version: '3.8'

services:
  web:
    build:
      context: ./app
    container_name: fastapi-app
    volumes:
      - ./app:/app
    networks:
      - corgi_network

  nginx:
    image: nginx:1.29.4-alpine-slim
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app/static:/usr/share/nginx/html/static:ro
    depends_on:
      - web
    networks:
      - corgi_network

networks:
  corgi_network:
    driver: bridge
